### ISSUE TITLE
Creating an API endpoint

### ISSUE THREAD

**Issue by Yukit02** [clitch-dev/clitch-api-spec#2]
# Task Summary

Title

## Subtasks

This ticket will be considered as finished when the following items are fulfilled:

- [ ] [create User Table]
- [ ] [GET api/user]
- [ ] [POST api/user]

## Implementation Scope

- Building a database(User)
- GET/POST response

## Difficulty

[5]

## Estimated Implementation Time

About 1 week
